# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedais', '0005_auto_20181006_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedal',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='pedal',
            unique_together=set([('grupo', 'destino')]),
        ),
    ]
